# Generated by Erlang.mk. Edit at your own risk!

src/base/get_web_handler.erl:: include/common.hrl; @touch $@
src/tools/time.erl:: include/common.hrl; @touch $@
src/tools/type.erl:: include/common.hrl; @touch $@

COMPILE_FIRST +=
